POST localhost:8080/api/events
Content-Type: application/json
Cookie: Idea-5081e67c=1baef0d0-e15d-498d-bebc-cc9aada4b0c9; flarum_session=NcBTSx1eVETtquD9UKZQlMMyz85wkypQw3kkSVDp
X-CSRF-Token: CQWB76F9VClXYPrutg30K8xm5tv1WDQB0SvZcL0H

{"data":{"type":"events","attributes":{"name": "New Event","description": "Test","event_start": "2020-07-10 10:00:00","event_end": "2020-07-10 17:00:00"}}}




###


